(define-module (fonts)
  #:use-module (ice-9 regex)
  #:use-module (guix utils)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix gexp)
  #:use-module (guix git-download)
  #:use-module (guix build-system font)
  #:use-module (guix build-system gnu)
  #:use-module (guix build-system meson)
  #:use-module (guix build-system trivial)
  #:use-module (gnu packages c)
  #:use-module (gnu packages base)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages compression)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages gettext)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages perl)
  #:use-module (gnu packages pkg-config)
  #:use-module (gnu packages python)
  #:use-module (gnu packages python-xyz)
  #:use-module (gnu packages xorg))

(define-public custom-font-ipamona
  (package
   (name "custom-font-ipamona")
   (version "1.0.8")
   (source
    (origin
     (method git-fetch)
     (uri (git-reference
           (url "https://github.com/ghost-of-freedom/font-ipamona")
           (commit "e82eb86b2feeba4527fff934051f7c5523356ff2")))
     (file-name (git-file-name name version))
     (sha256
      (base32 "1nd3q6yv8iixm1z88qf44xc7h5inmy1shsyn7lciblyn31cjx8gw"))))
   (build-system font-build-system)
   (home-page "https://web.archive.org/web/20190326123924/http://www.geocities.jp/ipa_mona/")
   (synopsis "Proportional IPA font version suitable for 2channel Shift_JIS art")
   (description "Proportional IPA font version suitable for 2channel Shift_JIS art")
   (license license:ipa)))
